### ISSUE TITLE
singleSEDfit error

### ISSUE THREAD

**Issue by yun201720** [aabdurrouf/piXedfit#10]
I have got the latest version of piXedfit, when I run singleSEDfit for the example fluxmap file, I got the KeyError:"Unable to open object (object 'gas_logu' doesn't exist)". I have tried to download the lastest model file from "https://drive.google.com/drive/folders/1YjZGg97dPT8S95NJmO5tiFH9jWhbxuVy?usp=sharing", but it does not work now. The page can not find now.

**Comment by aabdurrouf** [comment]
Sorry for the outdated link that I forgot to change. You can download model files from this repository https://github.com/aabdurrouf/restspec_models/tree/main. However, this is not mandatory to download these files and put it into /piXedfit/data/mod/ directory as you can actually generate model files yourself depending on your assumed parameter ranges using this function https://pixedfit.readthedocs.io/en/latest/piXedfit_model.html#piXedfit.piXedfit_model.save_models_rest_spec
