### ISSUE TITLE
keyError of img_process.reduced_stamps()

### ISSUE THREAD

**Issue by 0xygens** [aabdurrouf/piXedfit#7]
When i run the image processing,it happens.
And i'm sure this filter is in the list_fliters(),why cant recognize？
No problem with the input cell.

$output_stamps = img_process.reduced_stamps()

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [26], in <cell line: 2>()
      1 # run
----> 2 output_stamps = img_process.reduced_stamps()

File ~/opt/anaconda3/envs/pixedfit/lib/python3.8/site-packages/piXedfit/piXedfit_images/images_process.py:178, in images_processing.reduced_stamps(self)
    173 	idfil_psfmatch = 0
    175 elif flag_psfmatch == 0:
    176 	####============== (2) PSF matching ============#####
    177 	##==> (a) Get filter index with largest PSF size:
--> 178 	idfil_psfmatch = get_largest_FWHM_PSF(filters=filters)
    179 	print ("[PSF matching to %s]" % filters[idfil_psfmatch])
    181 	##==> (b) Get Kernels:

File ~/opt/anaconda3/envs/pixedfit/lib/python3.8/site-packages/piXedfit/piXedfit_images/images_utils.py:1137, in get_largest_FWHM_PSF(filters)
   1135 fil_fwhm = np.zeros(nbands)
   1136 for bb in range(0,nbands):
-> 1137 	fil_fwhm[bb] = col_fwhm_psf[filters[bb]]
   1139 idx_fil_max, max_val = max(enumerate(fil_fwhm), key=itemgetter(1))
   1141 return idx_fil_max

KeyError: 'hst_wfc3_uvis_f275w'

**Comment by aabdurrouf** [comment]
Can you please provide information on your input configuration (something like in 3rd cell in this example: https://github.com/aabdurrouf/piXedfit/blob/main/examples/FUVtoNIR_CALIFA/Step2_img_proc.ipynb)?

**Comment by 0xygens** [comment]
OK, The following is the input configuration like 3rd cell, no error.

Maybe I have too few filters
That just a try for two bands to use pixedfit ,Because of the other question, what kind of array i should input in filter_wave and filter_transmission of add_filter.

------------------------------------------------------------------------------------------------------------------
#call images_processing 
from piXedfit.piXedfit_images import images_processing 
import warnings
warnings.filterwarnings('ignore')

#list the filters 
filters = ['hst_wfc3_uvis_f336w','hst_wfc3_uvis_f275w'] 

#input science images 
sci_img = {} 
sci_img['hst_wfc3_uvis_f275w'] = 'skybgsub_hst_13340_01_wfc3_uvis_f275w_drz.fits' 
sci_img['hst_wfc3_uvis_f336w'] = 'skybgsub_hst_13340_01_wfc3_uvis_f336w_drz.fits' 

#input Variance images 
var_img = {}

var_img['hst_wfc3_uvis_f275w'] = 'var_WHT_hst_13340_01_wfc3_uvis_f275w_drz.fits' 
var_img['hst_wfc3_uvis_f336w'] = 'var_WHT_hst_13340_01_wfc3_uvis_f336w_drz.fits' 

#NGC 5194 galaxy coordinate 
gal_ra = 202.484170 # RA 
gal_dec = 47.230560 # DEC 

#input img_unit 
img_unit={}

img_unit['hst_wfc3_uvis_f275w']="erg/s/cm2/A"
img_unit['hst_wfc3_uvis_f336w']="erg/s/cm2/A"

#input img_scale 
img_scale={}

img_scale['hst_wfc3_uvis_f275w']=3.1858499e+18
img_scale['hst_wfc3_uvis_f336w']=1.26612e+18

#input kernels 
kernels= {}

kernels['hst_wfc3_uvis_f336w']='kernel_f336w_to_f275w.fits'

#redshift of the galaxy 
gal_z = 0.075000 

#size of the final stamps will be produced 
stamp_size = [131,131]

**Comment by aabdurrouf** [comment]
Thanks for reporting this. I have made a little update in images_process.py that hopefully will resolve this issue. Please clone and install piXedfit again as you did last time. Then you can try running image processing again using your current input configuration. Using two filters should not be a problem, I think. Please let me know if you still encounter any problem.

**Comment by 0xygens** [comment]
Thank you very much for your timely feedback on my questions！
But I'm sorry I still didn't succeed.
It looks like the cutout2D didn't align at the same spot, maybe because the psf match didn't work by my input kernel ?
This is the result of the run：

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
$# run
$output_stamps = img_process.reduced_stamps()
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

[PSF matching to hst_wfc3_uvis_f275w]

---------------------------------------------------------------------------
NoOverlapError                            Traceback (most recent call last)
Input In [15], in <cell line: 2>()
      1 # run
----> 2 output_stamps = **img_process.reduced_stamps()**

File ~/opt/anaconda3/envs/pixedfit/lib/python3.8/site-packages/piXedfit/piXedfit_images/images_process.py:242, in images_processing.reduced_stamps(self)
    240 gal_x, gal_y = wcs.wcs_world2pix(gal_ra, gal_dec, 1)
    241 position = (gal_x,gal_y)
--> 242 cutout = **Cutout2D(hdu.data, position=position, size=(dim_y1,dim_x1), wcs=wcs)**
    243 hdu.data = cutout.data 
    244 hdu.header.update(cutout.wcs.to_header())

File ~/opt/anaconda3/envs/pixedfit/lib/python3.8/site-packages/astropy/nddata/utils.py:571, in Cutout2D.__init__(self, data, position, size, wcs, mode, fill_value, copy)
    567 # reverse position because extract_array and overlap_slices
    568 # use (y, x), but keep the input position
    569 pos_yx = position[::-1]
--> 571 cutout_data, input_position_cutout = **extract_array(**
    572     **data, tuple(shape), pos_yx, mode=mode, fill_value=fill_value,**
    573     **return_position=True)**
    574 if copy:
    575     cutout_data = np.copy(cutout_data)

File ~/opt/anaconda3/envs/pixedfit/lib/python3.8/site-packages/astropy/nddata/utils.py:216, in extract_array(array_large, shape, position, mode, fill_value, return_position)
    213 if mode not in ['partial', 'trim', 'strict']:
    214     raise ValueError("Valid modes are 'partial', 'trim', and 'strict'.")
--> 216 large_slices, small_slices = **overlap_slices(array_large.shape,**
    217                                             **shape, position, mode=mode)**
    218 extracted_array = array_large[large_slices]
    219 if return_position:

File ~/opt/anaconda3/envs/pixedfit/lib/python3.8/site-packages/astropy/nddata/utils.py:112, in overlap_slices(large_array_shape, small_array_shape, position, mode)
    110 for e_min, large_shape in zip(indices_min, large_array_shape):
    111     if e_min >= large_shape:
--> 112         raise NoOverlapError('Arrays do not overlap.')
    114 if mode == 'strict':
    115     for e_min in indices_min:

NoOverlapError: Arrays do not overlap.

**Comment by sabygoswami** [comment]
You can try checking the WCS if the right header is being read. For HST datasets, it's generally different from the other cases. 
Basically try checking "hdu[0].header" argument if it needs to be hdu[0].header or hdu[1].header and so on.

**Comment by 0xygens** [comment]
Thanks very much for the author's quick reply. The problem has been solved well. The error of the second problem is not from the pixedfit function
